# tripleo-quickstart-interop.yml

# Add the virthost to the in-memory inventory.  The inventory is not
# wirtten out to disk unless you call the `rebuild-inventory` role.
- name: Add the virthost to the inventory
  hosts: localhost
  tasks:
    - add_host:
        name: "{{virthost}}"
        groups: "virthost"
        ansible_fqdn: "{{ virthost }}"
        ansible_user: "root"
        ansible_host: "{{ virthost }}"

# Add the undercloud node to the generated
# inventory.
- name:  Inventory the undercloud
  hosts: localhost
  gather_facts: yes
  vars:
      inventory: undercloud
  roles:
    - { role: tripleo-inventory, tags: ['undercloud-scripts'] }

# Generate MAC addresses that we'll use for the overcloud nodes.
# By generating these in advance we can populate the
# `instackenv.json` file with MAC addresses without running
# introspection.
#- name: get a list of MACs to use for overcloud
#  hosts: localhost
#  gather_facts: yes
#  tasks:
#    - when: overcloud_nodes
#      block:
#        - name: get a list of MACs to use
#          generate_macs:
#            nodes: "{{ overcloud_nodes }}"
#            networks: "{{ networks }}"
#          register: node_mac_map

# Generate the `instackenv.json` configuration file.  Note that this
# task *must* occur after the above overcloud tasks, because if
# `overcloud_nodes` is defined the template depends on the
# `node_mac_map` variable.
- name: Write instackenv script
  hosts: localhost
  tasks:
    - template:
        src: "{{ undercloud_instackenv_template }}"
        dest: "{{ working_dir }}/instackenv.json"

# Copy `instackenv.json` configuration file to the undercloud node
- name: Copy instackenv script to undercloud
  hosts: undercloud
  tasks:
    - copy: src={{ working_dir }}/instackenv.json dest=/home/stack/instackenv.json owner=stack group=stack

# DEPLOY ALL THE THINGS!  Depending on the currently selected set of
# tags, this will deploy the undercloud, deploy the overcloud, and
# perform some validation tests on the overcloud.
- name:  Install undercloud and deploy overcloud
  hosts: undercloud
  gather_facts: no
  roles:
    - tripleo/undercloud
    - tripleo/overcloud

# Add the overcloud nodes to the generated inventory.
- name:  Inventory the overcloud
  hosts: undercloud
  gather_facts: yes
  vars:
      inventory: all
  roles:
    - { role: tripleo-inventory, tags: ['overcloud-deploy'] }



